import { Box, Button, Container, Link, TextField } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import NextLink from 'next/link';
import { SubmitHandler, useForm } from 'react-hook-form';
import { useCreateUser } from '../hooks/use-create-user';

type IFormInputs = {
  name: string;
  email: string;
  password: string;
};

const SignUp: NextPage = () => {
  const { register, handleSubmit } = useForm<IFormInputs>();
  const { mutate } = useCreateUser();

  const onSubmit: SubmitHandler<IFormInputs> = async user => {
    mutate({ ...user, roles: ['user'] });
  };

  return (
    <Container
      maxWidth="md"
      style={{
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100vh',
      }}
    >
      <Head>
        <title>Bike Rentals - Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>

      <section>
        <Box
          component="form"
          onSubmit={handleSubmit(onSubmit)}
          sx={{
            '& .MuiTextField-root': { m: 1, width: '50ch' },
          }}
          noValidate
          autoComplete="off"
        >
          <Box style={{ flexDirection: 'column', display: 'flex' }}>
            <TextField
              {...register('name', { required: true })}
              required
              id="name"
              type="text"
              label="Name"
              fullWidth
            />
            <TextField
              {...register('email', { required: true })}
              required
              id="email"
              type="email"
              label="Email"
            />
            <TextField
              {...register('password', { required: true })}
              required
              type="password"
              id="password"
              label="Password"
            />
          </Box>
          <Box style={{ margin: '8px' }}>
            <Button
              type="submit"
              variant="outlined"
              style={{ marginBottom: '12px' }}
            >
              Sign up
            </Button>
            <br />
            <NextLink href="/sign-in">
              <Link color="inherit" href="#!">
                Already have an account ?
              </Link>
            </NextLink>
          </Box>
        </Box>
      </section>
    </Container>
  );
};

export default SignUp;
