import { Box, Button, Modal } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Menu } from '../components/menu';
import {
  ISaveUserFormInputs,
  SaveUserForm
} from '../components/save-user-form';
import { UsersList } from '../components/users-list';
import { useCreateUser } from '../hooks/use-create-user';

const modalStyle = {
  position: 'absolute' as 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)',
  bgcolor: 'background.paper',
  boxShadow: 24,
  p: 4,
};

const Users: NextPage = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const { mutateAsync, error, isLoading, reset } = useCreateUser();

  const handleSubmit = async (user: ISaveUserFormInputs) => {
    try {
      await mutateAsync(user);
      reset();
      toggleModal();
    } catch (err: any) {
      reset();
      console.log(err?.message, 'save error');
    }
  };

  const toggleModal = () => setIsModalOpen(oldValue => !oldValue);

  return (
    <div>
      <Head>
        <title>Bike Rentals - Users management</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu>
        <Modal
          open={isModalOpen}
          onClose={toggleModal}
          aria-labelledby="modal-modal-title"
          aria-describedby="modal-modal-description"
        >
          <Box sx={modalStyle}>
            <SaveUserForm
              title="Create new user"
              isLoading={isLoading}
              onSubmit={handleSubmit}
              error={error?.message}
            />
          </Box>
        </Modal>

        <Button onClick={toggleModal} variant="contained" size="large">
          Add new user
        </Button>

        <Box sx={{ marginTop: 2 }}>
          <UsersList />
        </Box>
      </Menu>
    </div>
  );
};

export default Users;
