import type { NextPage } from 'next';
import Head from 'next/head';
import { Menu } from '../components/menu';

const Users: NextPage = () => (
  <div>
    <Head>
      <title>Bike Rentals - Users management</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Menu>
      <h1>Users</h1>
    </Menu>
  </div>
);

export default Users;
